### ISSUE TITLE
On initial page load first click fails

### ISSUE THREAD

**Issue by gnuschichten** [gnuschichten/clipboard#1]
On initial page load first click fails, User need to click again to get a value.

Behaviour occours on all browser.

**Comment by spinal-tap** [comment]
Hi, 
have you tried fixing it?
Thanks

**Comment by gnuschichten** [comment]
Yes, it took a little longer. Merged to dev branch.

**Comment by gnuschichten** [comment]
Merged to main.

The plugin must be deactivated and activated once for the changes to take effect.
